@extends('referrals.layout')
@section('title', $case->reference)
@section('content')
<div class="referral-title"><div><a class="referral-link" href="{{ route('agent.dashboard') }}"><x-heroicon-o-arrow-left class="h-4 w-4" />আমার রেফারেল</a><h1>{{ $case->reference }}</h1></div><span class="referral-badge">{{ \App\Models\ReferralCase::statuses()[$case->status] }}</span></div>
<dl class="referral-details"><div><dt>রোগী</dt><dd>{{ $case->patient->name }}</dd></div><div><dt>হাসপাতাল</dt><dd>{{ $case->hospital?->name ?? 'নির্ধারিত নয়' }}</dd></div><div><dt>কমিশনের হার</dt><dd>{{ $case->commission_rate_bps === null ? 'নির্ধারিত নয়' : \App\Support\ReferralMoney::format($case->commission_rate_bps).'%' }}</dd></div><div><dt>হার গ্রহণের তারিখ</dt><dd>{{ $case->rate_acknowledged_at?->format('d M Y') ?? 'অপেক্ষমাণ' }}</dd></div></dl>
@if($case->commission_rate_bps !== null && ! $case->rate_acknowledged_at)
<section class="referral-band"><h2>কমিশনের শর্ত</h2><p>এই কেসে হাসপাতাল থেকে Asian Health Connect-এর বাস্তবে প্রাপ্ত কমিশনের {{ \App\Support\ReferralMoney::format($case->commission_rate_bps) }}% আপনার অংশ। এটি রোগীর চিকিৎসার মোট বিলের শতাংশ নয়। সেবা সম্পন্ন, প্রাপ্তি যাচাই এবং অনুমোদনের পর পরিশোধযোগ্য হবে। ফেরত বা সংশোধন হলে হিসাব সমন্বয় হবে।</p>
<form class="referral-form" method="post" action="{{ route('agent.acknowledge', $case->reference) }}">@csrf<input type="hidden" name="rate_version" value="{{ $case->rate_version }}"><label class="referral-check"><input type="checkbox" name="agree" value="1" required><span>এই কেসের হার ও শর্তে আমি সম্মত।</span></label><button class="referral-button"><x-heroicon-o-check class="h-4 w-4" />হার গ্রহণ করুন</button></form></section>
@endif
<dl class="referral-metrics"><div><dt>সম্ভাব্য হিসাব</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['calculated']) }}</dd></div><div><dt>পরিশোধিত</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['paid']) }}</dd></div><div><dt>অনুমোদিত অপরিশোধিত</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['payable']) }}</dd></div></dl>
<h2>পেমেন্টের ইতিহাস</h2><div class="referral-table-wrap"><table class="referral-table"><thead><tr><th>তারিখ</th><th>ধরন</th><th>টাকা (BDT)</th><th>রেফারেন্স</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->occurred_on->format('d M Y') }}</td><td>{{ $payment->type === 'payout' ? 'পরিশোধ' : 'পরিশোধ সংশোধন' }}</td><td>{{ \App\Support\ReferralMoney::format($payment->amount_minor) }}</td><td>{{ $payment->reference }}</td></tr>@empty<tr><td colspan="4">এখনো পেমেন্ট হয়নি।</td></tr>@endforelse</tbody></table></div>
@endsection
