@extends('referrals.layout')
@section('title', 'এজেন্ট ব্যবস্থাপনা')
@section('content')
<div class="referral-title"><h1>এজেন্ট</h1><a href="#agent-form" class="referral-link"><x-heroicon-o-plus class="h-4 w-4" />এজেন্টের তথ্য</a></div>
<div class="referral-table-wrap"><table class="referral-table"><thead><tr><th>এজেন্ট</th><th>যোগাযোগ</th><th>জেলা</th><th>অবস্থা</th><th>কেস</th><th>অ্যাকশন</th></tr></thead><tbody>
@forelse($agents as $agent)<tr><td>{{ $agent->business_name }}<small>{{ $agent->name }} · {{ $agent->code }}</small></td><td>{{ $agent->email }}<small>{{ $agent->phone }}</small></td><td>{{ $agent->district }}</td><td><span class="referral-badge">{{ $agent->is_active ? 'সক্রিয়' : 'অনুমোদন বাকি / নিষ্ক্রিয়' }}</span></td><td>{{ $agent->cases_count }}</td><td><div class="referral-actions"><a class="referral-icon" title="এজেন্ট সম্পাদনা" aria-label="{{ $agent->name }} সম্পাদনা" href="{{ route('referral-ops.agents', ['edit' => $agent->id]) }}#agent-form"><x-heroicon-o-pencil-square class="h-5 w-5" /></a>@if($agent->is_active)<form method="post" action="{{ route('referral-ops.agents.invite', $agent) }}">@csrf<button class="referral-icon" title="পাসওয়ার্ড লিংক পাঠান" aria-label="{{ $agent->name }}-কে পাসওয়ার্ড লিংক পাঠান"><x-heroicon-o-envelope class="h-5 w-5" /></button></form>@endif</div></td></tr>@empty<tr><td colspan="6" class="referral-empty">এখনো কোনো এজেন্ট নেই।</td></tr>@endforelse
</tbody></table></div><div class="mt-5">{{ $agents->links() }}</div>
<section id="agent-form" class="referral-band"><div class="referral-title"><h2>{{ $editing ? 'এজেন্ট সম্পাদনা' : 'নতুন এজেন্ট' }}</h2>@if($editing)<a href="{{ route('referral-ops.agents') }}#agent-form" class="referral-link">নতুন এজেন্ট</a>@endif</div>
<form method="post" action="{{ route('referral-ops.agents.save') }}" class="referral-form">@csrf<input type="hidden" name="agent_id" value="{{ $editing?->id }}"><div class="referral-form-grid">
@foreach(['name' => 'নাম', 'business_name' => 'প্রতিষ্ঠানের নাম', 'email' => 'ইমেইল', 'phone' => 'ফোন', 'district' => 'জেলা'] as $field => $label)<label>{{ $label }}<input name="{{ $field }}" type="{{ $field === 'email' ? 'email' : 'text' }}" required value="{{ old($field, $editing?->{$field}) }}"></label>@endforeach
<label>ঠিকানা<textarea name="address" rows="2">{{ old('address', $editing?->address) }}</textarea></label><label>যাচাইকৃত পেমেন্ট তথ্য<textarea name="payment_details" rows="2">{{ old('payment_details', $editing?->payment_details) }}</textarea></label><label>অনুমোদন<select name="is_active"><option value="0" @selected(! old('is_active', $editing?->is_active))>অনুমোদন বাকি / নিষ্ক্রিয়</option><option value="1" @selected(old('is_active', $editing?->is_active))>অনুমোদিত ও সক্রিয়</option></select></label><label class="referral-span">পরিবর্তনের কারণ / যাচাইয়ের তথ্য<textarea name="reason" required maxlength="1000" rows="2">{{ old('reason') }}</textarea></label></div><button class="referral-button"><x-heroicon-o-check class="h-4 w-4" />সংরক্ষণ করুন</button></form></section>
@endsection
