@extends('referrals.layout')
@section('title', $case->reference)
@section('content')
<div class="referral-title"><div><a class="referral-link" href="{{ route('referral-ops.index') }}"><x-heroicon-o-arrow-left class="h-4 w-4" />কেসসমূহ</a><h1>{{ $case->reference }}</h1></div><span class="referral-badge">{{ \App\Models\ReferralCase::statuses()[$case->status] }}</span></div>
<dl class="referral-details"><div><dt>রোগী</dt><dd>{{ $case->patient->name }}</dd></div><div><dt>যোগাযোগ</dt><dd>{{ $case->patient->phone }}</dd></div><div><dt>জেলা</dt><dd>{{ $case->patient->district ?? '—' }}</dd></div><div><dt>রেফারার</dt><dd>{{ $case->agent->business_name }}<br>{{ $case->agent->code }}</dd></div><div><dt>জমার সময় / উৎস</dt><dd>{{ $case->created_at->format('d M Y H:i') }} · {{ $case->source }}</dd></div><div><dt>যাচাইয়ের সময়</dt><dd>{{ $case->verified_at?->format('d M Y H:i') ?? 'অপেক্ষমাণ' }}</dd></div></dl>
@if($case->request_summary)<p class="referral-muted">{{ $case->request_summary }}</p>@endif
@if($hasDuplicates)<div class="referral-errors" role="status">একই ফোন নম্বরে আগের রেফারেল আছে। {{ $owner ? 'পরিচয় ও আগের কেস যাচাই প্রয়োজন।' : 'সুপার অ্যাডমিনের পরিচয় যাচাই প্রয়োজন।' }}</div>@endif
<nav class="referral-actions" aria-label="কেসের বিভাগ"><a class="referral-link" href="#case-progress">অগ্রগতি</a>@if($owner)<a class="referral-link" href="#case-commission">কমিশন</a><a class="referral-link" href="#case-payments">লেনদেন</a>@endif<a class="referral-link" href="#case-history">ইতিহাস</a></nav>
<section class="referral-band" id="case-progress"><h2>অগ্রগতি ও দায়িত্ব</h2><form class="referral-form" method="post" action="{{ route('referral-ops.progress', $case) }}">@csrf<div class="referral-form-grid">
<label>অবস্থা<select name="status">@foreach(\App\Models\ReferralCase::statuses() as $key => $label)<option value="{{ $key }}" @selected(old('status', $case->status) === $key)>{{ $label }}</option>@endforeach</select></label>
<label>পরবর্তী যোগাযোগ<input type="date" name="follow_up_on" value="{{ old('follow_up_on', $case->follow_up_on?->format('Y-m-d')) }}"></label>
@if($owner)
<label>দায়িত্বপ্রাপ্ত<select name="assigned_to"><option value="">নির্ধারিত নয়</option>@foreach($staff as $person)<option value="{{ $person->id }}" @selected(old('assigned_to', $case->assigned_to) == $person->id)>{{ $person->name }}</option>@endforeach</select></label>
<label>অনুমোদিত রেফারার<select name="agent_id" @disabled($case->verified_at || $case->rate_locked_at)>@foreach($agents as $agent)<option value="{{ $agent->id }}" @selected(old('agent_id', $case->agent_id) == $agent->id)>{{ $agent->business_name }}</option>@endforeach</select></label>
@endif
@foreach(['hospital_id' => ['হাসপাতাল', $hospitals], 'treatment_id' => ['ট্রিটমেন্ট', $treatments]] as $field => [$label, $options])
<label>{{ $label }}<select name="{{ $field }}" @disabled($case->verified_at)><option value="">নির্ধারিত নয়</option>@foreach($options as $option)<option value="{{ $option->id }}" @selected(old($field, $case->{$field}) == $option->id)>{{ $option->name }}</option>@endforeach</select></label>
@if($case->verified_at)<input type="hidden" name="{{ $field }}" value="{{ $case->{$field} }}">@endif
@endforeach
@if($owner && $hasDuplicates)
<label>পরিচয়ের সিদ্ধান্ত<select name="identity_resolution"><option value="">যাচাই বাকি</option><option value="new_patient">একই ফোন, ভিন্ন রোগী</option><option value="existing_patient_new_case">একই রোগীর নতুন চিকিৎসার কেস</option><option value="duplicate">একই কেসের পুনরায় জমা</option></select></label>
<label>সম্পর্কিত আগের কেস<select name="related_case_id"><option value="">নির্বাচন করুন</option>@foreach($duplicates as $duplicate)<option value="{{ $duplicate->id }}">{{ $duplicate->reference }} · {{ $duplicate->patient->name }}</option>@endforeach</select></label>
@endif
<label class="referral-span">কাজের আপডেট / পরিবর্তনের কারণ<textarea name="note" required maxlength="2000" rows="3">{{ old('note') }}</textarea></label>
</div>
<label class="referral-check"><input type="checkbox" name="confirm_contact" value="1" @checked($case->consent_confirmed_at)><span>রোগী / অনুমোদিত অভিভাবকের সঙ্গে কথা বলে যোগাযোগের সম্মতি ও রেফারার নিশ্চিত করেছি।</span></label>
<label class="referral-check"><input type="checkbox" name="confirm_sharing" value="1" @checked($case->sharing_confirmed_at)><span>নির্বাচিত হাসপাতালে প্রয়োজনীয় তথ্য পাঠানোর আলাদা সম্মতি নিশ্চিত করেছি।</span></label>
<button class="referral-button"><x-heroicon-o-check class="h-4 w-4" />অগ্রগতি সংরক্ষণ</button></form></section>
@if($owner)
<section class="referral-band" id="case-commission"><div class="referral-title"><h2>এই কেসের কমিশন</h2><span class="referral-badge">হিসাবের মুদ্রা: BDT</span></div>
<dl class="referral-details"><div><dt>এজেন্টের প্রযোজ্য হার</dt><dd>{{ $case->commission_rate_bps === null ? 'নির্ধারিত নয়' : \App\Support\ReferralMoney::format($case->commission_rate_bps).'%' }}</dd></div><div><dt>হারের উৎস</dt><dd>{{ $case->commission_rule_id ? 'নিয়ম #'.$case->commission_rule_id : ($case->rate_locked_at ? 'কেসের বিশেষ হার' : 'যাচাই অপেক্ষমাণ') }}</dd></div><div><dt>এজেন্টের সম্মতি</dt><dd>{{ $case->rate_acknowledged_at?->format('d M Y H:i') ?? 'অপেক্ষমাণ' }}</dd></div></dl>
<dl class="referral-metrics"><div><dt>হাসপাতাল থেকে নিট প্রাপ্ত কমিশন</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['received']) }}</dd></div><div><dt>এজেন্টের হিসাবকৃত অংশ</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['calculated']) }}</dd></div><div><dt>অনুমোদিত অপরিশোধিত</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['payable']) }}</dd></div><div><dt>মোট অনুমোদিত (বর্তমান যোগ্যতা)</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['approved']) }}</dd></div><div><dt>নিট পরিশোধিত</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['paid']) }}</dd></div><div><dt>যোগ্যতা / অনুমোদন অপেক্ষমাণ</dt><dd>৳{{ \App\Support\ReferralMoney::format($balance['pending']) }}</dd></div></dl>
@if($balance['overpaid'])<div class="referral-errors">সংশোধনের পরে অতিরিক্ত পরিশোধিত: ৳{{ \App\Support\ReferralMoney::format($balance['overpaid']) }}। সমন্বয় বাকি।</div>@endif
<form class="referral-form" method="post" action="{{ route('referral-ops.finance', $case) }}">@csrf<input type="hidden" name="action" value="override"><div class="referral-form-grid"><label>এই কেসের বিশেষ হার (%)<input name="percentage" type="number" required min="0" max="100" step="0.01" value="{{ $case->commission_rate_bps === null ? '' : $case->commission_rate_bps / 100 }}"></label><label>হার পরিবর্তনের কারণ ও সম্মত শর্ত<input name="reason" required maxlength="2000"></label></div><button class="referral-button secondary"><x-heroicon-o-pencil-square class="h-4 w-4" />কেসের হার পরিবর্তন</button></form>
@if($case->commission_rate_bps !== null && ! $case->rate_acknowledged_at)
<form class="referral-form" method="post" action="{{ route('referral-ops.finance', $case) }}">@csrf<input type="hidden" name="action" value="acknowledge"><input type="hidden" name="rate_version" value="{{ $case->rate_version }}"><label>অফলাইনে এজেন্টের সম্মতির প্রমাণ / চুক্তি ও তারিখ<input name="reason" required maxlength="2000"></label><button class="referral-button secondary"><x-heroicon-o-check-badge class="h-4 w-4" />প্রাপ্ত সম্মতি নথিভুক্ত</button></form>
@endif
<form class="referral-form" method="post" action="{{ route('referral-ops.finance', $case) }}">@csrf<input type="hidden" name="action" value="approve"><label>কমিশন অনুমোদনের নোট<input name="reason" required maxlength="2000"></label><button class="referral-button"><x-heroicon-o-check-circle class="h-4 w-4" />যোগ্য পাওনা অনুমোদন</button></form>
</section>
<section class="referral-band"><h2>এই কেসে হাসপাতালের চুক্তি</h2>@if($case->agreement_snapshot)<dl class="referral-details"><div><dt>রেফারেন্স</dt><dd>{{ $case->agreement_snapshot['contract_reference'] }}</dd></div><div><dt>হাসপাতাল থেকে আমাদের হার</dt><dd>{{ \App\Support\ReferralMoney::format($case->agreement_snapshot['rate_bps']) }}%</dd></div><div><dt>হিসাবের ভিত্তি</dt><dd>{{ $case->agreement_snapshot['basis'] }}</dd></div></dl>@else<p class="referral-muted">কেস গ্রহণের সময় কোনো কার্যকর হাসপাতাল চুক্তি পাওয়া যায়নি।</p>@endif</section>
<section class="referral-band" id="case-payments"><h2>হাসপাতালের প্রাপ্তি / এজেন্টের পেমেন্ট রেকর্ড</h2><form class="referral-form" method="post" action="{{ route('referral-ops.finance', $case) }}">@csrf<input type="hidden" name="action" value="entry"><input type="hidden" name="operation_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><div class="referral-form-grid">
<label>ধরন<select name="type"><option value="receipt">হাসপাতাল থেকে কমিশন বাস্তবে পাওয়া গেছে</option><option value="payout">এজেন্টকে টাকা পরিশোধ করা হয়েছে</option></select></label><label>হিসাবের অঙ্ক (BDT)<input name="amount" type="number" min="0.01" max="999999999.99" step="0.01" required></label>
<label>লেনদেনের রেফারেন্স<input name="reference" required maxlength="120"></label><label>লেনদেনের তারিখ<input name="occurred_on" type="date" required max="{{ today()->toDateString() }}" value="{{ today()->toDateString() }}"></label>
<label>হাসপাতাল থেকে প্রাপ্ত মূল মুদ্রা<select name="original_currency">@foreach(['BDT','INR','USD','THB','SGD','MYR','CNY'] as $currency)<option value="{{ $currency }}">{{ $currency }}</option>@endforeach</select></label><label>মূল মুদ্রায় প্রাপ্ত অঙ্ক<input name="original_amount" type="number" min="0.01" step="0.01"></label>
<label class="referral-span">প্রাপ্তি / পেমেন্ট যাচাই ও মুদ্রা রূপান্তরের নোট<textarea name="note" required rows="2" maxlength="2000"></textarea></label></div><button class="referral-button"><x-heroicon-o-banknotes class="h-4 w-4" />লেনদেন নথিভুক্ত করুন</button></form></section>
<div class="referral-table-wrap"><table class="referral-table"><thead><tr><th>তারিখ</th><th>ধরন</th><th>টাকা (BDT)</th><th>মূল অঙ্ক</th><th>রেফারেন্স</th><th>নোট / প্রাপক</th><th>সংশোধন</th></tr></thead><tbody>@forelse($entries as $entry)<tr><td>{{ $entry->occurred_on->format('d M Y') }}</td><td>{{ ['receipt'=>'হাসপাতালের প্রাপ্তি','payout'=>'এজেন্ট পেমেন্ট','receipt_reversal'=>'প্রাপ্তি রিভার্স','payout_reversal'=>'পেমেন্ট রিভার্স'][$entry->type] }}</td><td>{{ \App\Support\ReferralMoney::format($entry->amount_minor) }}</td><td>{{ $entry->original_currency }} {{ $entry->original_minor ? \App\Support\ReferralMoney::format($entry->original_minor) : '' }}</td><td>{{ $entry->reference }}</td><td>{{ $entry->note }}@if($entry->payee_snapshot)<small>{{ $entry->payee_snapshot }}</small>@endif</td><td>@if(in_array($entry->type,['receipt','payout']) && ! $entry->reversal)<details><summary class="referral-link">রিভার্স</summary><form class="referral-form" method="post" action="{{ route('referral-ops.finance', $case) }}">@csrf<input type="hidden" name="action" value="reverse"><input type="hidden" name="entry_id" value="{{ $entry->id }}"><label>কারণ<input name="reason" required maxlength="2000"></label><button class="referral-button secondary">রিভার্স নথিভুক্ত</button></form></details>@elseif($entry->reversal)রিভার্স হয়েছে@endif</td></tr>@empty<tr><td colspan="7">কোনো লেনদেন নেই।</td></tr>@endforelse</tbody></table></div>
@endif
<section class="referral-band" id="case-history"><h2>কেসের ইতিহাস</h2>@include('referrals.audit-table')</section>
@endsection
