@extends('referrals.layout')
@section('title', 'কমিশন ও চুক্তি')
@section('content')
<h1>কমিশন ও চুক্তি</h1>
<section class="referral-band"><h2>এজেন্টের নতুন হার</h2><form class="referral-form" method="post" action="{{ route('referral-ops.rules.save') }}">@csrf<div class="referral-form-grid">
<label>এজেন্ট<select name="agent_id" required><option value="">নির্বাচন করুন</option>@foreach($agents as $agent)<option value="{{ $agent->id }}" @selected(old('agent_id') == $agent->id)>{{ $agent->business_name }} · {{ $agent->code }}</option>@endforeach</select></label>
<label>হাসপাতাল<select name="hospital_id"><option value="">সব হাসপাতাল</option>@foreach($hospitals as $hospital)<option value="{{ $hospital->id }}" @selected(old('hospital_id') == $hospital->id)>{{ $hospital->name }}</option>@endforeach</select></label>
<label>ট্রিটমেন্ট<select name="treatment_id"><option value="">সব ট্রিটমেন্ট</option>@foreach($treatments as $treatment)<option value="{{ $treatment->id }}" @selected(old('treatment_id') == $treatment->id)>{{ $treatment->name }}</option>@endforeach</select></label>
<label>আমাদের প্রাপ্ত কমিশনে এজেন্টের অংশ (%)<input type="number" name="percentage" required min="0" max="100" step="0.01" value="{{ old('percentage') }}"></label>
<label>কার্যকর হওয়ার সময়<input type="datetime-local" name="effective_from" required value="{{ old('effective_from', now()->format('Y-m-d\TH:i')) }}"></label><label>সম্মত শর্ত / পরিবর্তনের কারণ<textarea name="reason" required rows="2" maxlength="1000">{{ old('reason') }}</textarea></label></div><button class="referral-button"><x-heroicon-o-plus class="h-4 w-4" />নতুন হার সংরক্ষণ</button></form></section>
<div class="referral-table-wrap"><table class="referral-table"><thead><tr><th>এজেন্ট</th><th>হাসপাতাল</th><th>ট্রিটমেন্ট</th><th>হার</th><th>কার্যকর</th><th>অবস্থা</th></tr></thead><tbody>@forelse($rules as $rule)<tr><td>{{ $rule->agent->business_name }}</td><td>{{ $rule->hospital?->name ?? 'সব' }}</td><td>{{ $rule->treatment?->name ?? 'সব' }}</td><td>{{ \App\Support\ReferralMoney::format($rule->rate_bps) }}%</td><td>{{ $rule->effective_from->format('d M Y H:i') }}</td><td>@if($rule->is_active)<details><summary class="referral-link">সক্রিয়</summary><form class="referral-form" method="post" action="{{ route('referral-ops.rules.disable', $rule) }}">@csrf<label>বন্ধ করার কারণ<input name="reason" required maxlength="1000"></label><button class="referral-button secondary">নিয়ম বন্ধ করুন</button></form></details>@else বন্ধ @endif</td></tr>@empty<tr><td colspan="6">এখনো কোনো নিয়ম নেই।</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $rules->links() }}</div>
<section class="referral-band"><h2>হাসপাতালের কমিশন চুক্তি</h2><form class="referral-form" method="post" action="{{ route('referral-ops.agreements.save') }}">@csrf<div class="referral-form-grid">
<label>হাসপাতাল<select name="hospital_id" required><option value="">নির্বাচন করুন</option>@foreach($hospitals as $hospital)<option value="{{ $hospital->id }}">{{ $hospital->name }}</option>@endforeach</select></label>
<label>ট্রিটমেন্ট<select name="treatment_id"><option value="">সব ট্রিটমেন্ট</option>@foreach($treatments as $treatment)<option value="{{ $treatment->id }}">{{ $treatment->name }}</option>@endforeach</select></label>
<label>হাসপাতাল থেকে আমাদের কমিশন (%)<input type="number" name="percentage" min="0" max="100" step="0.01" required></label><label>চুক্তির রেফারেন্স<input name="contract_reference" required maxlength="190"></label><label>কার্যকর হওয়ার সময়<input type="datetime-local" name="effective_from" required value="{{ now()->format('Y-m-d\TH:i') }}"></label><label class="referral-span">হিসাবের ভিত্তি, বাদযোগ্য খরচ ও পরিশোধের শর্ত<textarea name="basis" required rows="3" maxlength="3000"></textarea></label></div><button class="referral-button"><x-heroicon-o-document-plus class="h-4 w-4" />চুক্তির সংস্করণ সংরক্ষণ</button></form></section>
<div class="referral-table-wrap"><table class="referral-table"><thead><tr><th>হাসপাতাল</th><th>ট্রিটমেন্ট</th><th>হার</th><th>চুক্তি</th><th>হিসাবের ভিত্তি</th><th>কার্যকর</th></tr></thead><tbody>@forelse($agreements as $agreement)<tr><td>{{ $agreement->hospital->name }}</td><td>{{ $agreement->treatment?->name ?? 'সব' }}</td><td>{{ \App\Support\ReferralMoney::format($agreement->rate_bps) }}%</td><td>{{ $agreement->contract_reference }}</td><td>{{ $agreement->basis }}</td><td>{{ $agreement->effective_from->format('d M Y') }}</td></tr>@empty<tr><td colspan="6">এখনো কোনো চুক্তি নেই।</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $agreements->links() }}</div>
@endsection
